<?php
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');

//not autoloading, so require

require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';


class Hashapi extends REST_Controller {
	
	//curl --header "Content-Type: application/json" --request POST --data '{"path":"/path/to/file", "hash":"md5offileasdf1234"}' http://localhost/api/hashapi/md5
	
	public function md5_post()
    {
        // $this->some_model->update_user( ... );

        if(null == ($this->post('type'))){
            $type = 'md5';
        } else {
            $type = $this->post('type');
        }

        $message = [
            'id' => $this->post('id'), // Automatically generated by the model
            'path' => $this->post('path'),
            'hash' => $this->post('hash'),
            'type' => $type,
            'message' => 'Added a resource'
        ];

        $this->load->database();

        $data = array(
            'machineID' =>  $message['id'],
            'path'      =>  $message['path'],
            'hash'      =>  $message['hash'],
            'type'      =>  $type
        );

        $str = $this->db->insert_string('hashes', $data);

        $query = $this->db->query($str);
        
        if($query) {
             $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
        } else {
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST);
        }

        
    }
}